Peer-graded Assignment: Course Project 1
=============================================
1. Loading and preprocessing the data

```{r, results='hide'}
library(readr)
activity <- read_csv("activity.csv")
```
2. What is mean total number of steps taken per day?

```{r}
## Calculate the total number of steps taken per day
stepsperday <- tapply(activity$steps, activity$date, sum, na.rm=TRUE)
```

```{r}
## Make a histogram of the total number of steps taken each day
hist(stepsperday, xlab="Steps per day")
```

```{r}
## Calculate and report the mean and median of the total number of steps taken per day
mean(stepsperday)
median(stepsperday)
```

3. What is the average daily activity pattern?

```{r}
##Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

##caculate the average of the same time interval every day 
averagesteps <- tapply(activity$steps, activity$interval, mean, na.rm=T)
hours <- as.numeric(names(averagesteps))
plot(hours, averagesteps, type="l", xlab="time of day (h)", ylab="average number of steps in 5-min interval", main="Daily activity pattern")
```

```{r}
## Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
maxsteps <-which.max(averagesteps)
names(maxsteps)
```

4. Imputing missing values

```{r}
## Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
sum(is.na(activity))
```

```{r}
## Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
StepsAverage <- aggregate(steps ~ interval, data = activity, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(activity)) {
    obs <- activity[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(StepsAverage, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    fillNA <- c(fillNA, steps)
}
```

```{r}
## Create a new dataset that is equal to the original dataset but with the missing data filled in.
new_activity <- activity
new_activity$steps <- fillNA
```

```{r}
## Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
stepsperday_new <- tapply(new_activity$steps, new_activity$date, sum, na.rm=TRUE)
hist(stepsperday_new, xlab="Steps per day")
mean(stepsperday_new)
median(stepsperday_new)
```

5. Are there differences in activity patterns between weekdays and weekends?
```{r}
## Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
day <- weekdays(activity$date)
daylevel <- vector()
        for (i in 1:nrow(activity)) {
                if (day[i] == "星期六") {
                  daylevel[i] <- "Weekend"
}               else if (day[i] == "星期天") {
        daylevel[i] <- "Weekend"
}       else {
        daylevel[i] <- "Weekday"
}
        }
extdata <- cbind(new_activity, daylevel)
```

```{r}
## Make a panel plot containing a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 
library(lattice)
stepsByDay <- aggregate(steps ~ interval + daylevel, data = new_activity, mean)
names(stepsByDay) <- c("interval", "daylevel", "steps")
xyplot(steps ~ interval | daylevel, stepsByDay, type = "l", layout = c(1, 2), xlab = "Interval", ylab = "Number of steps")
```